version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      # Upgrade pip
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip

      # Set up a virtual environment
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV

      # Explicitly install conflicting packages
      - run:
          name: Install conflicting packages
          command: |
            pip install packaging==20.4 platformdirs==2.0

      # Upgrade pytest-selenium
      - run:
          name: Upgrade pytest-selenium
          command: pip install --upgrade pytest-selenium

      # Install dependencies from requirements.txt
      - run:
          name: Install dependencies from requirements.txt
          command: pip install -r requirements.txt

      # Set environment variables and run tests
      - run:
          name: Run tests with environment variables
          command: |
            TEST_ENV=aws APP_TYPE=member SUBDOMAIN=oshuk-759-1 CLUSTER=uat DOMAIN=teladoc.io pytest tests/test_registration.py --alluredir=./results_directory

      # Generate Allure report
      - run:
          name: Generate Allure report
          command: allure generate ./results_directory -o ./allure-report

      # Store the Allure report as an artifact
      - store_artifacts:
          path: ./allure-report
          destination: allure-report

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
